### ISSUE TITLE
YAML设置问题

### ISSUE THREAD

**Issue by StevenChen16** [StevenChen16/Halo-2.20.9#5]
### 前置条件

- [X] 已经在 [issues](https://github.com/halo-dev/halo/issues) 列表中搜索了相关问题。
- [X] 这是 Halo 项目本身存在的问题，如果是非项目本身的问题（如：安装部署问题），建议在 [Discussions](https://github.com/halo-dev/halo/discussions) 提交。
- [X] 已经尝试过停用所有的插件，排除是插件导致的问题。
- [X] 如果是插件和主题的问题，请在对应的插件和主题仓库提交。

### 系统信息

2.20.9

### 使用的哪种方式运行？

Source Code

### 发生了什么？

当正常启动的时候：
root@VM-4-14-ubuntu:~/app# java -Dfile.encoding=UTF-8 -jar halo-2.20.9-SNAPSHOT.jar --spring.config.additional-location=optional:file:$HOME/halo2-dev/
11:22:05.309 [main] ERROR org.springframework.boot.SpringApplication -- Application run failed
org.yaml.snakeyaml.constructor.DuplicateKeyException: while constructing a mapping
 in 'reader', line 1, column 1:
    server:
    ^
found duplicate key spring
 in 'reader', line 120, column 1:
    spring:
    ^

### 复现步骤

直接运行：
java -Dfile.encoding=UTF-8 -jar halo-2.20.9-SNAPSHOT.jar --spring.config.additional-location=optional:file:$HOME/halo2-dev/

### 相关日志输出

```shell
root@VM-4-14-ubuntu:~/app# java -Dfile.encoding=UTF-8 -jar halo-2.20.9-SNAPSHOT.jar --spring.config.additional-location=optional:file:$HOME/halo2-dev/
11:22:05.309 [main] ERROR org.springframework.boot.SpringApplication -- Application run failed
org.yaml.snakeyaml.constructor.DuplicateKeyException: while constructing a mapping
 in 'reader', line 1, column 1:
    server:
    ^
found duplicate key spring
 in 'reader', line 120, column 1:
    spring:
    ^
```

### 附加信息

有一个配置文件，保存在$HOME/halo2-dev/application.yaml：
```yaml
server:
  # 运行端口
  port: 8090
spring:
  # 数据库配置，支持 MySQL、MariaDB、PostgreSQL、H2 Database，具体配置方式可以参考下面的数据库配置
  r2dbc:
    url: r2dbc:h2:file:///${halo.work-dir}/db/halo-next?MODE=MySQL&DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: 123456
  sql:
    init:
      mode: always
      # 需要配合 r2dbc 的配置进行改动
      platform: h2
halo:
  caches:
    page:
      # 是否禁用页面缓存
      disabled: true
  # 工作目录位置
  work-dir: ${user.home}/.halo2
  # 外部访问地址
  external-url: http://localhost:8090
  # 附件映射配置，通常用于迁移场景
  attachment:
    resource-mappings:
      - pathPattern: /upload/**
        locations:
          - migrate-from-1.x
  ```
